version: "3.1"
services:
  db:
    image: redis/redis-stack:7.2.0-v6
    ports:
      - $REDIS_PORT:6379
      - 8001:8001
    environment:
      REDIS_ARGS: "--requirepass pass-redis-stack"
  back:
    env_file: .env
    build:
      dockerfile: Dockerfile
    links:
      - db:db  
    depends_on:
      - db
    ports:
      - 8000:80
